### ISSUE TITLE
Unable to Pretrain BERT using run_pretraining_lamb.sh

### ISSUE THREAD

**Issue by Esaada** [NVIDIA/DeepLearningExamples#503]
I followed the steps described in the quickstart in Bert's Readme:
[(https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT#quick-start-guide.)]
After a long preprocessing fight , I finally got to pertaining part I used this line:
`bash scripts/run_pretraining_lamb.sh 64 8 8 7.5e-4 5e-4 fp32 true 8 2000 200 7820 100 128 512 large`

I'm getting two errors;
>Traceback (most recent call last):
  File "/workspace/bert/run_pretraining.py", line 30, in <module>
    import utils.dllogger_class
ModuleNotFoundError: No module named 'utils.dllogger_class'

I tried to google it but I got only java stuff..
And :
>Error! /results/tf_bert_pretraining_lamb_large_fp32_gbs165536_gbs232768_200514070735/phase_1/model.ckpt-7038.meta directory missing. Please mount correctly

I'm using 8 V100 (not DGX) with 16gb.
The container is as requested. 
**tf version:**1.14
I'll be happy for your help.
Thanks.

**Comment by swethmandava** [comment]
Fixed in #502

**Comment by Esaada** [comment]
Not working for me, my updated repo from this moment:
![up2date_repo](https://user-images.githubusercontent.com/23050230/82116042-587d6b80-976f-11ea-91d7-09351440297c.PNG)
Still getting the error:
![stillgettingerror](https://user-images.githubusercontent.com/23050230/82116054-6d59ff00-976f-11ea-91d8-4dc11eec7429.PNG)

**Comment by swethmandava** [comment]
the MR had not been merged yet. Try to git pull again and verify your git log to make sure.
